config/routes.rb
Begin::Application.routes.draw do
  get "welcome/index"
  
  resources :posts do
  	resources :comments
  end
  
  get 'readfiles' => 'readfiles#index'
  match 'readfiles/open', to: 'readfiles#index', via: [:get, :post]

  root to: "welcome#index"
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	validates :title, presence: true,
    		length: { minimum: 5 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
  		@posts = Post.all
	end

	def new
		@post = Post.new
    end

    def create
    	#render text: params[:post].inspect
    	@post = Post.new(post_params)

  		if @post.save
 			#redirect_to @post
 			#render 'show'
 			redirect_to posts_path
 		else
    		render 'new'
    	end
    end

	def show
	  	@post = Post.find(params[:id])
	end

	def edit
      	@post = Post.find(params[:id])
    end

	def update
	  	@post = Post.find(params[:id])

	  	if @post.update(post_params)
	    	redirect_to @post
	  	else
	    	render 'edit'
	  	end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		respond_to do |format|
          	format.html { redirect_to posts_url }
        	format.json { head :no_content }
        end
	end

  #######################
	#######################
  def update_db(hash)
    (query(hash).any?) ? renew(hash) : add(hash)
  end

	def add(hash)
		puts '#############################################'
		puts 'inside Post add(hash)'
		puts '#############################################'

    # To-do: indicate what to add in what columns
		# post = Post.new({ title: hash[:title], text: hash[:text].to_s })
		# post.save

    #########################
    hash[:text].each do |t|
      post = Post.new({ title: hash[:title], text: t.to_s })
      post.save
    end
    #########################
	end

	def renew(hash)
		puts '#############################################'
		puts 'inside Post renew(hash)'
		puts '#############################################'

    target_posts = query(hash)
    if target_posts.many?
      target_posts.each do |post|
        # To-do: indicate what to update in what columns
        post.update({ title: hash[:title], text: hash[:text].to_s+'[--]updated' })
      end
    else
      # To-do: indicate what to update in what columns
      Post.update( target_posts, { title: hash[:title], text: hash[:text].to_s+'[--]updated' })
    end
	end

	def query(hash)
    puts '#############################################'
    puts 'inside Post query(hash)'
    puts '#############################################'

    Post.where(title: hash[:title])
	end
	#######################
  #######################

  private
  	def post_params
  		params.require(:post).permit(:title, :text)
  	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= form_for :post, url: post_path(@post.id) ,method: :patch do |f| %>
  <% if @post.errors.any? %>
   <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= link_to 'Main', root_path %>
<%= link_to "My Blog", controller: "posts" %>
<%= link_to 'Read File', readfiles_path %>
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h3>Comments</h3>
<%= render @post.comments %>

<h3>Add a comment:</h3>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> 
<%= link_to 'Back', posts_path %>